services:
  postgres-dwh:
    image: postgres:13
    container_name: postgres-dwh
    environment:
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwh
      POSTGRES_DB: dwh
    ports:
      - "5433:5432"
    volumes:
      - postgres-dwh-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dwh"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - easydatapipeline_default

volumes:
  postgres-dwh-volume:
    driver: local

networks:
  easydatapipeline_default:
    external: true
